# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # install dependencies
      - node/install:
          install-yarn: true
          node-version: 19.4.0
      - run: node --version
      - run:
          name: run "yarn install node-modules"
          command: yarn install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # run test suite
      - run:
          name: Run tests with JUnit as reporter
          command: yarn run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test_reports/
      - store_test_results:
          path: ./test_reports/
