# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@19.4.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - node/install:
            install-yarn: true
            node-version: 19.4.0
              - run: node --version
      - run: yarn install
      - run: yarn test
